import Homepage from '@/components/Homepage'
import Content from '@/components/Content'
import Head from 'next/head'
import Activities from '@/components/Activities'
import Tastet from '@/components/Tastet'
import Contact from '@/components/Contact'
import Medias from '@/components/Medias'
import Weather from '@/components/Weather'
import 'mapbox-gl/dist/mapbox-gl.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Novelle Farm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="robots" content="noindex" />
      </Head>
      <Homepage />
      <Content />
      <Activities />
      <Tastet />
      <Medias />
      <Contact />
      <Weather />
    </>
  )
}
