import Homepage from '@/components/Homepage'
import Content from '@/components/Content'
import Head from 'next/head'
import Activities from '@/components/Activities'

export default function Home() {
  return (
    <>
      <Head>
        <title>Novelle Farm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage />
      <Content />
      <Activities />
    </>
  )
}
